# fly.toml app configuration file generated for chat-sanbox on 2025-05-08T23:00:55+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chat-sanbox'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
